services:
  - type: web
    name: kleenai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PROJECT_NAME
        value: kleenai Backend
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.jccjchbpwgcjscfklfpn:UCHEadiyo%40bonga2025@aws-1-eu-west-1.pooler.supabase.com:6543/postgres
      - key: SYNC_DATABASE_URL
        value: postgresql://postgres.jccjchbpwgcjscfklfpn:UCHEadiyo%40bonga2025@aws-1-eu-west-1.pooler.supabase.com:5432/postgres
      - key: SUPABASE_URL
        value: https://jccjchbpwgcjscfklfpn.supabase.co
      - key: FIREBASE_PROJECT_ID
        value: kleenai
      - key: GEMINI_API_KEY
        sync: false
