include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "ios/**"
    - "android/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Custom rules
